name: Build mkdocs site and upload to S3

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION : "us-east-1"
  BUCKET_NAME: "demo-mkdocs-multibranch-deploy-custom-s3bucketroot-2cizqidtbjyx"

permissions:
  id-token: write
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Build site
        run: mkdocs build
      
      - name: Deploy
        id: deploy
        uses: dyadyaJora/s3-multibranch-deploy-preview@main
        with:
          aws_region: "${{ env.AWS_REGION }}"
          aws_assume_role: "${{ secrets.ASSUME_ROLE }}"
          aws_bucket: "${{ env.BUCKET_NAME }}"
          folder: "site"
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          enable_comment: "true"

      - name: Print LAB DOCS_LINK
        run: |
          echo "Docs deploy is available at ${{steps.deploy.outputs.preview_url}}"
